version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install --legacy-peer-deps
      - save_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      # Add back in once tests are created
      # - run:
      #     command: npm run test
      #     name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Firebase CLI
          command: npm install -g firebase-tools
      - run:
          name: Firebase Deploy
          command: firebase deploy --token=$FIREBASE_TOKEN
workflows:
  build_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
